language: java
sudo: required
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - wget https://github.com/hivdb/nucamino/releases/download/v0.1.3/nucamino-linux-amd64 -O $NUCAMINO_PROGRAM
  - chmod 755 $NUCAMINO_PROGRAM
env:
  global:
    - |-
      NUCAMINO_PROGRAM="${TRAVIS_BUILD_DIR}/nucamino"
script:
  - ./gradlew assemble
  - ./gradlew -D java.util.concurrent.ForkJoinPool.common.parallelism=2 check
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7af6ff72-0786-4e60-b368-760b022dacc9 || echo "Codecov did not collect coverage reports"
